export { default as InConstruction } from './InConstruction/InConstruction'
export { default as HomeScreen } from './home/HomeScreen'
export { default as homeStyle } from './home/homeStyle'
export { default as LoginScreen } from './login/LoginScreen'
export { default as loginStyle } from './login/loginStyle'
export { default as RegisterScreen } from './register/RegisterScreen'
export { default as styleRegister } from './register/styleRegister'
