export { default as StyledButton } from './styledComponents/styledButton/StyledButton'
export { default as styleButton } from './styledComponents/styledButton/styleButton'
export { default as StyledInput } from './styledComponents/styledInput/StyledInput'
export { default as styleInput } from './styledComponents/styledInput/styleInput'
export { default as StyledText } from './styledComponents/styledText/StyledText'
export { default as styleText } from './styledComponents/styledText/styleText'
