export { default as Email } from './Email'
export { default as Eye } from './Eye'
export { default as HiRobot } from './HiRobot'
export { default as Key } from './Key'
export { default as Person } from './Person'
export { default as Phone } from './Phone'
export { default as RegisterRobot } from './RegisterRobot'
export { default as RobotPlaying } from './RobotPlaying'
